apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-api
  template:
    metadata:
      labels:
        app: echo-api
    spec:
      containers:
        - name: http-echo
          image: hashicorp/http-echo
          args:
            - "-text=hello from hashicorp echo"
          ports:
            - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: echo-api
spec:
  selector:
    app: echo-api
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678
      nodePort: 30080  # Optional: use a fixed port, or omit for random (range: 30000–32767)
