replicaCount: 1

computerName: qemu1

qemu:
  image: qemux/qemu
  vnc_port: 5900
  boot: ubuntu
  storageSize: 20Gi

vnc_ws_proxy:
  # Minikube
  image: lukaskellerstein/vnc-ws-proxy:0.0.6
  # AKS
  # image: lukaskellerstein/vnc-ws-proxy:0.0.7

  listen_host: "0.0.0.0"
  listen_port: 7500
  vnc_port: 5900