apiVersion: v1
kind: Pod
metadata:
  name: my-server-pod
  labels:
    app: my-server
spec:
  containers:
    - name: my-server-container
      image: lukaskellerstein/simple-http-server:0.0.1
      env:
        - name: PORT
          value: "8080"
      # Optional: used for documentation, health probes, or when using tools like `kubectl expose`
      # Do not affect the container's behavior
      # ports:
      #   - containerPort: 8080  
