apiVersion: v1
kind: Service
metadata:
  name: {{ include "proxy.name" . }}
spec:
  selector:
    app: {{ include "proxy.name" . }}
  ports:
    - name: websocket
      port: {{ .Values.vnc_ws_proxy.listen_port }}
      targetPort: {{ .Values.vnc_ws_proxy.listen_port }}
    