apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.computerName }}-pvc"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.dockur.storageSize }}