version: "3.9"
services:
  db:
    container_name: car-db
    image: mongo
    ports:
      - "27017:27017"
  api:
    container_name: car-api
    image: lukaskellerstein/car-api:0.0.1
    # build: ./api
    environment:
      - PORT=8000
      - DB_URL=car-db
      - DB_PORT=27017
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
    depends_on:
      - db
    ports:
      - "8000:8000"
  app:
    container_name: car-app
    image: lukaskellerstein/car-app:0.0.1
    # build: ./app
    environment:
      - API_URL=car-api
      - API_PORT=8000
    depends_on:
      api:
        condition: service_healthy
  ui:
    container_name: car-ui
    image: lukaskellerstein/car-ui:0.0.1
    # build: ./ui
    environment:
      - PORT=5000
      - API_URL=car-api
      - API_PORT=8000
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "5000:5000"