apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order
          image: lukaskellerstein/ecomm-order-svc:0.0.1
          env:
            - name: MONGO_URI
              value: mongodb://mongodb:27017
          ports:
            - containerPort: 50052
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: ecommerce
spec:
  selector:
    app: order-service
  ports:
    - port: 50052
      targetPort: 50052
