apiVersion: apps/v1
kind: Deployment
metadata:
  name: windows1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: windows1
  template:
    metadata:
      labels:
        app: windows1
    spec:
      containers:

        - name: windows
          image: dockurr/windows
          env:
          - name: VERSION
            value: "11"
          - name: DISK_SIZE
            value: "64G"
          volumeMounts:
            - name: storage
              mountPath: /storage
            - name: dev-tun
              mountPath: /dev/net/tun
            # AKS
            - name: dev-kvm
              mountPath: /dev/kvm
          
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN"]
          # Optional
          # ports:
          # - containerPort: 8006
          #   name: http
          #   protocol: TCP
          # - containerPort: 3389
          #   name: rdp
          #   protocol: TCP
          # - containerPort: 3389
          #   name: udp
          #   protocol: UDP
          # - containerPort: 5900
          #   name: vnc
          #   protocol: TCP

      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: windows1-pvc
        - name: dev-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
        # AKS
        - name: dev-kvm
          hostPath:
            path: /dev/kvm
        
---
apiVersion: v1
kind: Service
metadata:
  name: windows1
spec:
  type: LoadBalancer
  selector:
    app: windows1
  ports:
    - name: http
      port: 8006
      protocol: TCP
      targetPort: 8006
    - name: rdp
      port: 3389
      protocol: TCP
      targetPort: 3389
    - name: udp
      port: 3389
      protocol: UDP
      targetPort: 3389
    - name: vnc
      port: 5900
      protocol: TCP
      targetPort: 5900
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: windows1-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi