apiVersion: apps/v1
kind: Deployment
metadata:
  name: qemu1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qemu1
  template:
    metadata:
      labels:
        app: qemu1
    spec:
      containers:

        - name: qemu
          image: qemux/qemu
          env:
            - name: BOOT
              value: "ubuntu"
          volumeMounts:
            - name: storage
              mountPath: /storage
            - name: dev-tun
              mountPath: /dev/net/tun
            # AKS
            # - name: dev-kvm
            #   mountPath: /dev/kvm

          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN"]
          # Optional
          # ports:
          # - containerPort: 8006
          #   name: http
          #   protocol: TCP
          # - containerPort: 5900
          #   name: vnc
          #   protocol: TCP

        - name: test-http-server
          image: lukaskellerstein/simple-http-server:0.0.1
          env:
          - name: PORT
            value: "8080"
          # Optional
          # ports:
          #   - containerPort: 8080

        - name: test-ws-server
          image: lukaskellerstein/simple-ws-server:0.0.1
          env:
          - name: PORT
            value: "7070"
          # Optional
          # ports:
          #   - containerPort: 7070

      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: qemu1-pvc
        - name: dev-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
        # AKS
        # - name: dev-kvm
        #   hostPath:
        #     path: /dev/kvm

---
apiVersion: v1
kind: Service
metadata:
  name: qemu1
spec:
  selector:
    app: qemu1
  ports:
    - name: qemu-vnc
      port: 5900
      targetPort: 5900
    - name: test-server-http
      port: 8001
      targetPort: 8080
    - name: test-server-ws
      port: 8002
      targetPort: 7070
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qemu1-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi