apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.carApi.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.carApi.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.carApi.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.carApi.name }}
    spec:
      containers:
        - name: {{ .Values.carApi.name }}
          image: {{ .Values.carApi.image }}
          env:
            - name: PORT
              value: "{{ .Values.carApi.port }}"
            - name: DB_URL
              value: "{{ .Values.carDb.name }}"
            - name: DB_PORT
              value: "{{ .Values.carDb.port }}"
          ports:
            - containerPort: {{ .Values.carApi.port | int }}
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: {{ .Values.carApi.port | int }}
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.carApi.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.carApi.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.carApi.port | int }}
      targetPort: {{ .Values.carApi.port | int }}
