apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.computerName }}
spec:
  selector:
    app: {{ .Values.computerName }}
  ports:
    - name: vnc
      protocol: TCP
      port: {{ .Values.qemu.vnc_port }}
      targetPort: {{ .Values.qemu.vnc_port }}
    