apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-sidecar-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-sidecar-1
  template:
    metadata:
      labels:
        app: test-sidecar-1
    spec:
      containers:
        - name: test-server-1
          image: lukaskellerstein/simple-http-server:0.0.1
          env:
          - name: PORT
            value: "8080"
          ports:
            - containerPort: 8080

        - name: test-server-2
          image: lukaskellerstein/simple-http-server:0.0.1
          env:
          - name: PORT
            value: "8081"
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: test-sidecar-1
spec:
  selector:
    app: test-sidecar-1
  ports:
    - name: http-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: http-8081
      protocol: TCP
      port: 8081
      targetPort: 8081

