apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ecommerce-ui-ingressroute
  namespace: {{ .Values.namespace }}
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`{{ .Values.ui.rootPath }}`)
      kind: Rule
      services:
        - name: ui
          port: {{ .Values.ui.port }}
