apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order
          image: {{ .Values.orderService.image }}
          env:
            - name: MONGO_URI
              value: mongodb://mongodb:{{ .Values.mongodb.port }}
          ports:
            - containerPort: {{ .Values.orderService.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: order-service
  ports:
    - port: {{ .Values.orderService.port }}
      targetPort: {{ .Values.orderService.port }}
