apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: {{ .Values.ui.image }}
          env:
            - name: URL_ROOT_PATH
              value: {{ .Values.ui.rootPath | quote }}
            - name: PORT
              value: "{{ .Values.ui.port }}"
            - name: PRODUCT_SERVICE_URL
              value: {{ .Values.ui.productServiceUrl | quote }}
            - name: ORDER_SERVICE_URL
              value: {{ .Values.ui.orderServiceUrl | quote }}
          ports:
            - containerPort: {{ .Values.ui.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: ui
  ports:
    - port: {{ .Values.ui.port }}
      targetPort: {{ .Values.ui.port }}
