apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-api
  template:
    metadata:
      labels:
        app: echo-api
    spec:
      containers:
        - name: http-echo
          image: hashicorp/http-echo
          args:
            - "-text=hello from hashicorp echo"
          ports:
            - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: echo-api
spec:
  selector:
    app: echo-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5678
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: echo-ingressroute
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/echo`)
      kind: Rule
      services:
        - name: echo-api
          port: 5000