apiVersion: v1
kind: Service
metadata:
  name: traefik-service
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  ports:
    - name: dashboard
      targetPort: dashboard
      port: 8080
    - name: web
      targetPort: web
      port: 80
    # - name: websecure
    #   targetPort: websecure
    #   port: 443
    - name: ws
      targetPort: ws
      port: 7777
  selector:
    app: traefik