apiVersion: v1
kind: Pod
metadata:
  name: my-servers-pod
  labels:
    app: my-servers
spec:
  containers:
    - name: my-http-server-container
      image: lukaskellerstein/simple-http-server:0.0.1
      env:
        - name: PORT
          value: "8080"
      # Optional: used for documentation, health probes, or when using tools like `kubectl expose`
      # Do not affect the container's behavior
      # ports:
      #   - containerPort: 8080  
    - name: my-ws-server-container
      image: lukaskellerstein/simple-ws-server:0.0.1
      env:
        - name: PORT
          value: "7070"
      # Optional: used for documentation, health probes, or when using tools like `kubectl expose`
      # Do not affect the container's behavior
      # ports:
      #   - containerPort: 7070  
