apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-api
  namespace: car
spec:
  replicas: 1
  selector:
    matchLabels:
      app: car-api
  template:
    metadata:
      labels:
        app: car-api
    spec:
      containers:
        - name: car-api
          image: lukaskellerstein/car-api:0.0.1
          env:
            - name: PORT
              value: "8000"
            - name: DB_URL
              value: "car-db"
            - name: DB_PORT
              value: "27017"
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: car-api
  namespace: car
spec:
  selector:
    app: car-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
