apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-db
  namespace: car
spec:
  replicas: 1
  selector:
    matchLabels:
      app: car-db
  template:
    metadata:
      labels:
        app: car-db
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: car-db
  namespace: car
spec:
  selector:
    app: car-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
