apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-sidecar-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-sidecar-2
  template:
    metadata:
      labels:
        app: test-sidecar-2
    spec:
      containers:
        - name: test-server-1
          image: lukaskellerstein/simple-http-server:0.0.1
          env:
          - name: PORT
            value: "8080"
          ports:
            - containerPort: 8080

        - name: test-server-2
          image: lukaskellerstein/simple-ws-server:0.0.1
          env:
          - name: PORT
            value: "7070"
          ports:
            - containerPort: 7070
---
apiVersion: v1
kind: Service
metadata:
  name: test-sidecar-2
spec:
  selector:
    app: test-sidecar-2
  ports:
    - name: http-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: ws-7070
      protocol: TCP
      port: 7070
      targetPort: 7070

