apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: traefik
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-account
      containers:
        - name: traefik
          image: {{ .Values.image }}
          args:
            - --api.insecure
            - --entrypoints.web.address=:80
            - --entrypoints.websecure.address=:443
            - --providers.kubernetesingress
            - --providers.kubernetesCRD.namespaces=
            - --providers.kubernetesIngress.namespaces=
          ports:
            - name: web
              containerPort: 80
            - name: dashboard
              containerPort: 8080