apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard-service
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  ports:
    - targetPort: dashboard
      port: 8080
  selector:
    app: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-web-service
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  ports:
    - targetPort: web
      port: 80
  selector:
    app: traefik