apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: admin-ui-ingressroute-http
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`{{ .Values.route }}`)
      kind: Rule
      services:
        - name: {{ .Values.name }}
          port: {{ .Values.port }}
